### ISSUE TITLE
Create fpgrars.toml file for project-wide configuration

### ISSUE THREAD

**Issue by LeoRiether** [LeoRiether/FPGRARS#38]
It would be nice to have a `fpgrars.toml` file, or something similar, to configure things that are currently passed by arguments in the CLI. For example, instead of passing `--width 720 --height 720 --scale 1` every time, `fpgrars.toml` could contain

```toml
width = 720
height = 720
scale = 1
```
